import type { PartnerApplication } from '@/lib/types';

export const mockApplications: PartnerApplication[] = [
  {
    id: 'APP001',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    status: 'Dalam Review',
    appliedAt: '2026-01-20T09:00:00Z',
    currentEvalStep: 6,
    totalEvalSteps: 13,
    documents: [
      { id: 'AD001', documentTypeId: 'akta_pendirian', name: 'Akta Pendirian PT PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD002', documentTypeId: 'siup', name: 'SIUP PT PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD003', documentTypeId: 'tdp_nib', name: 'NIB PT PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD004', documentTypeId: 'npwp', name: 'NPWP PT PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD005', documentTypeId: 'laporan_keuangan', name: 'Laporan Keuangan 2023-2025', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD006', documentTypeId: 'referensi_bank', name: 'Referensi Bank Mandiri', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD007', documentTypeId: 'pengalaman_kerja', name: 'Daftar Pengalaman Kerja', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD008', documentTypeId: 'sertifikat_iso', name: 'ISO 9001:2015 & ISO 14001:2015', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD009', documentTypeId: 'amdal_ukl_upl', name: 'Dokumen UKL-UPL', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD010', documentTypeId: 'profil_perusahaan', name: 'Company Profile PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD011', documentTypeId: 'struktur_organisasi', name: 'Struktur Organisasi PGN', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD012', documentTypeId: 'daftar_peralatan', name: 'Daftar Peralatan Utama', status: 'Diunggah', uploadDate: '2026-01-20' },
      { id: 'AD013', documentTypeId: 'daftar_tenaga_ahli', name: 'Daftar Tenaga Ahli', status: 'Diunggah', uploadDate: '2026-01-20' },
    ],
  },
  {
    id: 'APP002',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk',
    projectId: 'P002',
    projectName: 'Kerjasama Gasifikasi Batubara',
    status: 'Dalam Review',
    appliedAt: '2025-12-10T08:30:00Z',
    currentEvalStep: 6,
    totalEvalSteps: 13,
    documents: [
      { id: 'AD014', documentTypeId: 'akta_pendirian', name: 'Akta Pendirian PT PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD015', documentTypeId: 'siup', name: 'SIUP PT PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD016', documentTypeId: 'tdp_nib', name: 'NIB PT PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD017', documentTypeId: 'npwp', name: 'NPWP PT PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD018', documentTypeId: 'laporan_keuangan', name: 'Laporan Keuangan 2022-2024', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD019', documentTypeId: 'referensi_bank', name: 'Referensi Bank Mandiri', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD020', documentTypeId: 'pengalaman_kerja', name: 'Pengalaman Kerja Gasifikasi', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD021', documentTypeId: 'sertifikat_iso', name: 'Sertifikat ISO PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD022', documentTypeId: 'amdal_ukl_upl', name: 'AMDAL PGN', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD023', documentTypeId: 'profil_perusahaan', name: 'Company Profile PGN 2025', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD024', documentTypeId: 'struktur_organisasi', name: 'Struktur Organisasi', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD025', documentTypeId: 'daftar_peralatan', name: 'Daftar Peralatan', status: 'Diunggah', uploadDate: '2025-12-10' },
      { id: 'AD026', documentTypeId: 'daftar_tenaga_ahli', name: 'Tenaga Ahli Gas', status: 'Diunggah', uploadDate: '2025-12-10' },
    ],
  },
  {
    id: 'APP003',
    partnerId: 'M005',
    partnerName: 'PT Indonesia Asahan Aluminium',
    projectId: 'P005',
    projectName: 'Rehabilitasi Lahan Pasca Tambang',
    status: 'Terpilih',
    appliedAt: '2024-02-01T10:00:00Z',
    currentEvalStep: 13,
    totalEvalSteps: 13,
    documents: [
      { id: 'AD027', documentTypeId: 'akta_pendirian', name: 'Akta Pendirian INALUM', status: 'Diunggah', uploadDate: '2024-02-01' },
      { id: 'AD028', documentTypeId: 'siup', name: 'SIUP INALUM', status: 'Diunggah', uploadDate: '2024-02-01' },
      { id: 'AD029', documentTypeId: 'laporan_keuangan', name: 'Laporan Keuangan 2021-2023', status: 'Diunggah', uploadDate: '2024-02-01' },
      { id: 'AD030', documentTypeId: 'profil_perusahaan', name: 'Company Profile INALUM', status: 'Diunggah', uploadDate: '2024-02-01' },
    ],
  },
  {
    id: 'APP004',
    partnerId: 'M006',
    partnerName: 'PT Perusahaan Nusantara Restu Energi',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    status: 'Dikirim',
    appliedAt: '2026-02-28T14:00:00Z',
    currentEvalStep: 2,
    totalEvalSteps: 13,
    documents: [
      { id: 'AD031', documentTypeId: 'akta_pendirian', name: 'Akta Pendirian PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD032', documentTypeId: 'siup', name: 'SIUP PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD033', documentTypeId: 'tdp_nib', name: 'NIB PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD034', documentTypeId: 'npwp', name: 'NPWP PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD035', documentTypeId: 'laporan_keuangan', name: 'Laporan Keuangan 2023-2025', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD036', documentTypeId: 'referensi_bank', name: 'Referensi Bank BCA', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD037', documentTypeId: 'pengalaman_kerja', name: 'Pengalaman Kerja PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD038', documentTypeId: 'profil_perusahaan', name: 'Company Profile PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD039', documentTypeId: 'struktur_organisasi', name: 'Struktur Organisasi PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD040', documentTypeId: 'daftar_peralatan', name: 'Daftar Peralatan PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD041', documentTypeId: 'daftar_tenaga_ahli', name: 'Tenaga Ahli PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD042', documentTypeId: 'amdal_ukl_upl', name: 'UKL-UPL PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
      { id: 'AD043', documentTypeId: 'sertifikat_iso', name: 'ISO 9001 PNRE', status: 'Diunggah', uploadDate: '2026-02-28' },
    ],
  },
  {
    id: 'APP005',
    partnerId: 'M006',
    partnerName: 'PT Perusahaan Nusantara Restu Energi',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    status: 'Terpilih',
    appliedAt: '2025-09-15T09:00:00Z',
    currentEvalStep: 13,
    totalEvalSteps: 13,
    documents: [
      { id: 'AD044', documentTypeId: 'akta_pendirian', name: 'Akta Pendirian PNRE', status: 'Diunggah', uploadDate: '2025-09-15' },
      { id: 'AD045', documentTypeId: 'laporan_keuangan', name: 'Laporan Keuangan PNRE', status: 'Diunggah', uploadDate: '2025-09-15' },
      { id: 'AD046', documentTypeId: 'profil_perusahaan', name: 'Company Profile PNRE', status: 'Diunggah', uploadDate: '2025-09-15' },
    ],
  },
];
