import { Approval } from '@/lib/types';

export const mockApprovals: Approval[] = [
  {
    id: 'APR-001',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    type: 'Persetujuan Akhir Pemilihan Mitra',
    status: 'Menunggu',
    requestedBy: 'Ratna Sari',
    requestedAt: '2026-02-20T09:00:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: undefined,
    notes: 'Menunggu persetujuan Ketua Tim untuk penetapan mitra PNRE pada proyek PLTS Tanjung Enim',
    priority: 'Tinggi',
    phase: 'phase2',
    approvalCategory: 'phase2_final',
  },
  {
    id: 'APR-002',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    type: 'Persetujuan Hasil Evaluasi Teknis',
    status: 'Disetujui',
    requestedBy: 'Siti Rahmawati',
    requestedAt: '2025-10-20T10:30:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: '2025-10-22T14:15:00Z',
    notes: 'Hasil evaluasi teknis PGN dan Medco Energi disetujui. PGN unggul dalam kapabilitas teknis.',
    priority: 'Tinggi',
    phase: 'phase2',
    approvalCategory: 'evaluasi',
  },
  {
    id: 'APR-003',
    projectId: 'P002',
    projectName: 'Kerjasama Gasifikasi Batubara',
    type: 'Persetujuan Shortlist Mitra',
    status: 'Menunggu',
    requestedBy: 'Siti Rahmawati',
    requestedAt: '2026-02-25T08:45:00Z',
    approver: 'Dr. Maya Putri',
    approvedAt: undefined,
    notes: 'Menunggu persetujuan Komisaris untuk shortlist mitra: PGN, INALUM, dan PNRE',
    priority: 'Tinggi',
    phase: 'phase1',
    approvalCategory: 'phase1_shortlist',
    evaluationSummary: {
      totalMitra: 3,
      lolos: 2,
      tidakLolos: 1,
    },
  },
  {
    id: 'APR-004',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    type: 'Persetujuan Hasil Evaluasi Keuangan',
    status: 'Disetujui',
    requestedBy: 'Ahmad Hidayat',
    requestedAt: '2025-11-01T11:00:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: '2025-11-03T09:30:00Z',
    notes: 'Evaluasi keuangan KEP-100 untuk PGN (Grade AA) dan Medco Energi (Grade AA) disetujui.',
    priority: 'Sedang',
    phase: 'phase2',
    approvalCategory: 'evaluasi',
  },
  {
    id: 'APR-005',
    projectId: 'P004',
    projectName: 'Coal-to-Methanol Plant',
    type: 'Persetujuan Inisiasi Proyek',
    status: 'Menunggu',
    requestedBy: 'Siti Rahmawati',
    requestedAt: '2026-01-15T13:00:00Z',
    approver: 'Dr. Maya Putri',
    approvedAt: undefined,
    notes: 'Menunggu persetujuan Komisaris untuk inisiasi proyek Coal-to-Methanol senilai Rp 2.5T',
    priority: 'Tinggi',
    approvalCategory: 'inisiasi',
  },
  {
    id: 'APR-006',
    projectId: 'P002',
    projectName: 'Kerjasama Gasifikasi Batubara',
    type: 'Persetujuan Hasil Evaluasi Legal',
    status: 'Dikembalikan',
    requestedBy: 'Dewi Lestari',
    requestedAt: '2026-01-10T10:00:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: undefined,
    notes: 'Dikembalikan: Perlu klarifikasi tambahan terkait sengketa lahan INALUM dan status perizinan PNRE. Mohon dilengkapi nota dinas penjelasan dari tim legal.',
    priority: 'Sedang',
    phase: 'phase2',
    approvalCategory: 'evaluasi',
  },
  {
    id: 'APR-007',
    projectId: 'P005',
    projectName: 'Rehabilitasi Lahan Pasca Tambang',
    type: 'Persetujuan Penutupan Proyek',
    status: 'Disetujui',
    requestedBy: 'Fitri Handayani',
    requestedAt: '2025-12-15T08:00:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: '2025-12-18T11:30:00Z',
    notes: 'Proyek rehabilitasi lahan pasca tambang telah selesai sesuai target. Persetujuan penutupan proyek diberikan.',
    priority: 'Rendah',
    approvalCategory: 'penutupan',
  },
  {
    id: 'APR-008',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    type: 'Persetujuan Dokumen Mitra',
    status: 'Ditolak',
    requestedBy: 'Ratna Sari',
    requestedAt: '2026-02-05T14:30:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: '2026-02-08T10:00:00Z',
    notes: 'Ditolak: Dokumen kelengkapan mitra PNRE belum memenuhi syarat. Laporan keuangan masih pending dan sertifikat ISO belum dilengkapi. Mohon mitra melengkapi dokumen terlebih dahulu.',
    priority: 'Sedang',
    phase: 'phase1',
    approvalCategory: 'dokumen',
  },
  {
    id: 'APR-009',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    type: 'Persetujuan Shortlist Mitra',
    status: 'Disetujui',
    requestedBy: 'Siti Rahmawati',
    requestedAt: '2025-09-15T09:00:00Z',
    approver: 'Ir. Bambang Wijaya',
    approvedAt: '2025-09-17T14:00:00Z',
    notes: 'Shortlist Fase 1 disetujui. Kedua mitra (PGN dan Medco Energi) memenuhi syarat dan lolos ke Fase 2.',
    priority: 'Tinggi',
    phase: 'phase1',
    approvalCategory: 'phase1_shortlist',
    evaluationSummary: {
      totalMitra: 2,
      lolos: 2,
      tidakLolos: 0,
    },
  },
];
