import { DashboardStats, SLAItem } from '@/lib/types';

export const dashboardStats: DashboardStats = {
  totalProjects: 5,
  projectsTrend: 12,
  activeEvaluations: 8,
  evaluationsTrend: -5,
  slaCompliance: 87.5,
  slaTrend: 3.2,
  pendingApprovals: 4,
  approvalsTrend: -15,
};

export const mockSLAItems: SLAItem[] = [
  {
    id: 'SLA-001',
    processName: 'Pembuatan Proyek',
    targetDays: 7,
    actualDays: 5,
    status: 'Tepat Waktu',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    startDate: '2025-09-01',
    dueDate: '2025-09-08',
  },
  {
    id: 'SLA-002',
    processName: 'Pendaftaran Mitra',
    targetDays: 21,
    actualDays: 18,
    status: 'Tepat Waktu',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    startDate: '2025-09-10',
    dueDate: '2025-10-01',
  },
  {
    id: 'SLA-003',
    processName: 'Upload Dokumen Mitra',
    targetDays: 14,
    actualDays: 12,
    status: 'Dalam Proses',
    projectName: 'Kerjasama Gasifikasi Batubara',
    startDate: '2026-02-25',
    dueDate: '2026-03-11',
  },
  {
    id: 'SLA-004',
    processName: 'Upload Dokumen Mitra',
    targetDays: 14,
    actualDays: 18,
    status: 'Terlambat',
    projectName: 'Coal-to-Methanol Plant',
    startDate: '2026-02-01',
    dueDate: '2026-02-15',
  },
  {
    id: 'SLA-005',
    processName: 'Evaluasi Nilai Mitra',
    targetDays: 21,
    actualDays: 17,
    status: 'Tepat Waktu',
    projectName: 'Solar Panel Farm Tanjung Enim',
    startDate: '2026-01-15',
    dueDate: '2026-02-05',
  },
  {
    id: 'SLA-006',
    processName: 'Evaluasi Nilai Mitra',
    targetDays: 21,
    actualDays: 15,
    status: 'Dalam Proses',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    startDate: '2026-02-20',
    dueDate: '2026-03-13',
  },
  {
    id: 'SLA-007',
    processName: 'Persetujuan Penunjukan Mitra',
    targetDays: 7,
    actualDays: 10,
    status: 'Terlambat',
    projectName: 'Coal-to-Methanol Plant',
    startDate: '2026-01-15',
    dueDate: '2026-01-22',
  },
  {
    id: 'SLA-008',
    processName: 'Persetujuan Penunjukan Mitra',
    targetDays: 7,
    actualDays: 5,
    status: 'Dalam Proses',
    projectName: 'Solar Panel Farm Tanjung Enim',
    startDate: '2026-02-20',
    dueDate: '2026-02-27',
  },
  {
    id: 'SLA-009',
    processName: 'Penunjukan Mitra',
    targetDays: 7,
    actualDays: 5,
    status: 'Tepat Waktu',
    projectName: 'Kerjasama Gasifikasi Batubara',
    startDate: '2026-01-20',
    dueDate: '2026-01-27',
  },
  {
    id: 'SLA-010',
    processName: 'Kontrak',
    targetDays: 14,
    actualDays: 11,
    status: 'Tepat Waktu',
    projectName: 'Rehabilitasi Lahan Pasca Tambang',
    startDate: '2025-12-05',
    dueDate: '2025-12-19',
  },
];
