import { DocumentItem } from '@/lib/types';

export interface DocumentWithMeta extends DocumentItem {
  partnerId: string;
  partnerName: string;
  projectId?: string;
  projectName?: string;
  uploadedBy?: string;
  fileSize?: string;
  versionHistory: {
    version: number;
    uploadDate: string;
    uploadedBy: string;
    notes: string;
    fileUrl: string;
  }[];
}

export const mockDocuments: DocumentWithMeta[] = [
  {
    id: 'DOC-M001-05',
    name: 'Laporan Keuangan 2023 - PGN',
    type: 'Laporan Keuangan',
    status: 'Lengkap',
    uploadDate: '2024-04-10',
    expiryDate: undefined,
    version: 3,
    fileUrl: '/docs/pgn/lapkeu-2023-v3.pdf',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Ir. Hendra Kusuma',
    fileSize: '4.2 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-04-10', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Upload awal laporan keuangan audited 2023', fileUrl: '/docs/pgn/lapkeu-2023-v1.pdf' },
      { version: 2, uploadDate: '2024-06-15', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Revisi sesuai koreksi auditor atas catatan atas laporan keuangan', fileUrl: '/docs/pgn/lapkeu-2023-v2.pdf' },
      { version: 3, uploadDate: '2024-08-20', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Versi final setelah persetujuan RUPS', fileUrl: '/docs/pgn/lapkeu-2023-v3.pdf' },
    ],
  },
  {
    id: 'DOC-M001-08',
    name: 'Sertifikat ISO 9001:2015 - PGN',
    type: 'Sertifikat ISO',
    status: 'Lengkap',
    uploadDate: '2024-03-18',
    expiryDate: '2026-09-30',
    version: 1,
    fileUrl: '/docs/pgn/iso-9001.pdf',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Ir. Hendra Kusuma',
    fileSize: '1.8 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-03-18', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Upload sertifikat ISO 9001:2015 dari BSI', fileUrl: '/docs/pgn/iso-9001.pdf' },
    ],
  },
  {
    id: 'DOC-M001-11',
    name: 'Profil Perusahaan PGN',
    type: 'Profil Perusahaan',
    status: 'Lengkap',
    uploadDate: '2024-07-10',
    expiryDate: undefined,
    version: 3,
    fileUrl: '/docs/pgn/profil-v3.pdf',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Ir. Hendra Kusuma',
    fileSize: '12.5 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-03-17', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Upload profil perusahaan awal', fileUrl: '/docs/pgn/profil-v1.pdf' },
      { version: 2, uploadDate: '2024-05-20', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Update data operasional dan keuangan terkini', fileUrl: '/docs/pgn/profil-v2.pdf' },
      { version: 3, uploadDate: '2024-07-10', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Penambahan informasi proyek baru dan pencapaian ESG', fileUrl: '/docs/pgn/profil-v3.pdf' },
    ],
  },
  {
    id: 'DOC-M003-05',
    name: 'Laporan Keuangan 2023 - AKR',
    type: 'Laporan Keuangan',
    status: 'Ditolak',
    uploadDate: '2024-08-20',
    expiryDate: undefined,
    version: 1,
    fileUrl: '/docs/akr/lapkeu-2023.pdf',
    partnerId: 'M003',
    partnerName: 'PT AKR Corporindo Tbk',
    projectId: 'P004',
    projectName: 'Coal-to-Methanol Plant',
    uploadedBy: 'Suryanto Wijaya',
    fileSize: '3.8 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-08-20', uploadedBy: 'Suryanto Wijaya', notes: 'Upload laporan keuangan - DITOLAK: Laporan belum diaudit oleh KAP terdaftar di OJK', fileUrl: '/docs/akr/lapkeu-2023.pdf' },
    ],
  },
  {
    id: 'DOC-M003-14',
    name: 'Daftar Tenaga Ahli - AKR',
    type: 'Daftar Tenaga Ahli',
    status: 'Ditolak',
    uploadDate: '2024-08-14',
    expiryDate: undefined,
    version: 1,
    fileUrl: '/docs/akr/tenaga-ahli.pdf',
    partnerId: 'M003',
    partnerName: 'PT AKR Corporindo Tbk',
    projectId: 'P004',
    projectName: 'Coal-to-Methanol Plant',
    uploadedBy: 'Suryanto Wijaya',
    fileSize: '2.1 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-08-14', uploadedBy: 'Suryanto Wijaya', notes: 'Upload daftar tenaga ahli - DITOLAK: Kualifikasi tenaga ahli bidang kimia dan petrokimia belum memenuhi persyaratan minimum', fileUrl: '/docs/akr/tenaga-ahli.pdf' },
    ],
  },
  {
    id: 'DOC-M004-07',
    name: 'Daftar Pengalaman Kerja - Medco',
    type: 'Daftar Pengalaman Kerja',
    status: 'Lengkap',
    uploadDate: '2024-09-05',
    expiryDate: undefined,
    version: 3,
    fileUrl: '/docs/medco/pengalaman-v3.pdf',
    partnerId: 'M004',
    partnerName: 'PT Medco Energi Internasional Tbk',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Dr. Lukman Mahfoedz',
    fileSize: '5.6 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-02-05', uploadedBy: 'Dr. Lukman Mahfoedz', notes: 'Upload daftar pengalaman kerja awal', fileUrl: '/docs/medco/pengalaman-v1.pdf' },
      { version: 2, uploadDate: '2024-05-15', uploadedBy: 'Dr. Lukman Mahfoedz', notes: 'Penambahan referensi proyek PLTU Tanjung Jati B', fileUrl: '/docs/medco/pengalaman-v2.pdf' },
      { version: 3, uploadDate: '2024-09-05', uploadedBy: 'Dr. Lukman Mahfoedz', notes: 'Update pencapaian proyek geothermal Ijen dan Sarulla', fileUrl: '/docs/medco/pengalaman-v3.pdf' },
    ],
  },
  {
    id: 'DOC-M005-05',
    name: 'Laporan Keuangan 2023 - INALUM',
    type: 'Laporan Keuangan',
    status: 'Lengkap',
    uploadDate: '2024-05-01',
    expiryDate: undefined,
    version: 2,
    fileUrl: '/docs/inalum/lapkeu-2023-v2.pdf',
    partnerId: 'M005',
    partnerName: 'PT Indonesia Asahan Aluminium (INALUM)',
    projectId: 'P002',
    projectName: 'Kerjasama Gasifikasi Batubara',
    uploadedBy: 'Ir. Parulian Simatupang',
    fileSize: '6.3 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-05-01', uploadedBy: 'Ir. Parulian Simatupang', notes: 'Upload laporan keuangan konsolidasi audited 2023', fileUrl: '/docs/inalum/lapkeu-2023-v1.pdf' },
      { version: 2, uploadDate: '2024-07-20', uploadedBy: 'Ir. Parulian Simatupang', notes: 'Revisi sesuai permintaan klarifikasi tim evaluasi keuangan PTBA', fileUrl: '/docs/inalum/lapkeu-2023-v2.pdf' },
    ],
  },
  {
    id: 'DOC-M006-05',
    name: 'Laporan Keuangan 2023 - PNRE',
    type: 'Laporan Keuangan',
    status: 'Pending',
    uploadDate: '2024-09-15',
    expiryDate: undefined,
    version: 1,
    fileUrl: '/docs/pnre/lapkeu-2023.pdf',
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    uploadedBy: 'Ir. Rachmad Hardadi',
    fileSize: '3.4 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-09-15', uploadedBy: 'Ir. Rachmad Hardadi', notes: 'Upload laporan keuangan 2023 - sedang dalam proses verifikasi oleh tim keuangan PTBA', fileUrl: '/docs/pnre/lapkeu-2023.pdf' },
    ],
  },
  {
    id: 'DOC-M006-08',
    name: 'Sertifikat ISO 14001:2015 - PNRE',
    type: 'Sertifikat ISO',
    status: 'Pending',
    uploadDate: undefined,
    expiryDate: undefined,
    version: 0,
    fileUrl: undefined,
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    uploadedBy: undefined,
    fileSize: undefined,
    versionHistory: [],
  },
  {
    id: 'DOC-M006-13',
    name: 'Daftar Peralatan - PNRE',
    type: 'Daftar Peralatan',
    status: 'Belum Upload',
    uploadDate: undefined,
    expiryDate: undefined,
    version: 0,
    fileUrl: undefined,
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    projectId: 'P003',
    projectName: 'Solar Panel Farm Tanjung Enim',
    uploadedBy: undefined,
    fileSize: undefined,
    versionHistory: [],
  },
  {
    id: 'DOC-M004-05',
    name: 'Laporan Keuangan 2023 - Medco',
    type: 'Laporan Keuangan',
    status: 'Lengkap',
    uploadDate: '2024-04-25',
    expiryDate: undefined,
    version: 2,
    fileUrl: '/docs/medco/lapkeu-2023-v2.pdf',
    partnerId: 'M004',
    partnerName: 'PT Medco Energi Internasional Tbk',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Dr. Lukman Mahfoedz',
    fileSize: '5.1 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-03-01', uploadedBy: 'Dr. Lukman Mahfoedz', notes: 'Upload laporan keuangan konsolidasi audited 2023', fileUrl: '/docs/medco/lapkeu-2023-v1.pdf' },
      { version: 2, uploadDate: '2024-04-25', uploadedBy: 'Dr. Lukman Mahfoedz', notes: 'Penyesuaian catatan atas laporan keuangan per permintaan evaluator', fileUrl: '/docs/medco/lapkeu-2023-v2.pdf' },
    ],
  },
  {
    id: 'DOC-M002-11',
    name: 'Profil Perusahaan BEI',
    type: 'Profil Perusahaan',
    status: 'Lengkap',
    uploadDate: '2024-08-12',
    expiryDate: undefined,
    version: 2,
    fileUrl: '/docs/bei/profil-v2.pdf',
    partnerId: 'M002',
    partnerName: 'PT Bursa Efek Indonesia (BEI)',
    projectId: undefined,
    projectName: undefined,
    uploadedBy: 'Drs. Agus Firmansyah',
    fileSize: '8.7 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-05-23', uploadedBy: 'Drs. Agus Firmansyah', notes: 'Upload profil perusahaan awal', fileUrl: '/docs/bei/profil-v1.pdf' },
      { version: 2, uploadDate: '2024-08-12', uploadedBy: 'Drs. Agus Firmansyah', notes: 'Update dengan informasi terbaru dan pencapaian 2024', fileUrl: '/docs/bei/profil-v2.pdf' },
    ],
  },
  {
    id: 'DOC-M001-09',
    name: 'Dokumen AMDAL - PGN',
    type: 'AMDAL/UKL-UPL',
    status: 'Lengkap',
    uploadDate: '2024-03-22',
    expiryDate: undefined,
    version: 1,
    fileUrl: '/docs/pgn/amdal.pdf',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    projectId: 'P001',
    projectName: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    uploadedBy: 'Ir. Hendra Kusuma',
    fileSize: '15.2 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-03-22', uploadedBy: 'Ir. Hendra Kusuma', notes: 'Upload dokumen AMDAL yang telah disetujui oleh KLHK', fileUrl: '/docs/pgn/amdal.pdf' },
    ],
  },
  {
    id: 'DOC-M005-08',
    name: 'Sertifikat ISO 45001:2018 - INALUM',
    type: 'Sertifikat ISO',
    status: 'Lengkap',
    uploadDate: '2024-04-08',
    expiryDate: '2026-12-31',
    version: 1,
    fileUrl: '/docs/inalum/iso-45001.pdf',
    partnerId: 'M005',
    partnerName: 'PT Indonesia Asahan Aluminium (INALUM)',
    projectId: 'P002',
    projectName: 'Kerjasama Gasifikasi Batubara',
    uploadedBy: 'Ir. Parulian Simatupang',
    fileSize: '2.3 MB',
    versionHistory: [
      { version: 1, uploadDate: '2024-04-08', uploadedBy: 'Ir. Parulian Simatupang', notes: 'Upload sertifikat ISO 45001:2018 Occupational Health & Safety', fileUrl: '/docs/inalum/iso-45001.pdf' },
    ],
  },
  {
    id: 'DOC-M003-09',
    name: 'Dokumen AMDAL - AKR',
    type: 'AMDAL/UKL-UPL',
    status: 'Belum Upload',
    uploadDate: undefined,
    expiryDate: undefined,
    version: 0,
    fileUrl: undefined,
    partnerId: 'M003',
    partnerName: 'PT AKR Corporindo Tbk',
    projectId: 'P004',
    projectName: 'Coal-to-Methanol Plant',
    uploadedBy: undefined,
    fileSize: undefined,
    versionHistory: [],
  },
];
