import { Evaluation } from '@/lib/types';

export const mockEvaluations: Evaluation[] = [
  {
    id: 'EVAL-001',
    projectId: 'P001',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 5.00, weight: 0.30, notes: 'PGN merupakan pemimpin pasar gas bumi nasional dengan pangsa pasar dominan' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 4.50, weight: 0.25, notes: 'Industri gas alam menunjukkan pertumbuhan positif seiring transisi energi' },
        { name: 'Reputasi & Brand Value', score: 5.00, weight: 0.25, notes: 'Brand BUMN terpercaya dengan reputasi sangat baik di sektor energi' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 5.00, weight: 0.20, notes: 'Jaringan pipa gas terluas di Indonesia dengan cakupan nasional' },
      ],
      total: 5.00,
      weight: 0.15,
      weightedScore: 0.75,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 4.50, weight: 0.30, notes: 'Memiliki teknologi gasifikasi dan pengolahan gas yang mumpuni' },
        { name: 'Pengalaman Proyek Sejenis', score: 4.00, weight: 0.25, notes: 'Pengalaman luas dalam proyek infrastruktur gas skala besar' },
        { name: 'Sumber Daya Manusia Teknis', score: 4.50, weight: 0.25, notes: 'Memiliki tenaga ahli bersertifikasi internasional yang memadai' },
        { name: 'Fasilitas & Peralatan', score: 4.00, weight: 0.20, notes: 'Fasilitas produksi dan peralatan memenuhi standar internasional' },
      ],
      total: 4.25,
      weight: 0.20,
      weightedScore: 0.85,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 4.00, weight: 0.40, notes: 'Program pengelolaan lingkungan baik, target net-zero 2060' },
        { name: 'Social (Sosial)', score: 4.50, weight: 0.30, notes: 'Program CSR aktif dan kontribusi sosial yang signifikan' },
        { name: 'Governance (Tata Kelola)', score: 4.50, weight: 0.30, notes: 'GCG rating sangat baik, transparansi laporan tinggi' },
      ],
      total: 4.33,
      weight: 0.10,
      weightedScore: 0.433,
    },
    financial: {
      indicators: [
        {
          name: 'Return on Equity (ROE)',
          formula: 'Net Income / Total Equity x 100%',
          values: [
            { year: 2021, value: 7.42, score: 12 },
            { year: 2022, value: 8.73, score: 14 },
            { year: 2023, value: 9.32, score: 15 },
          ],
          weight: 15,
          averageScore: 13.67,
        },
        {
          name: 'Return on Investment (ROI)',
          formula: 'EBIT / Total Assets x 100%',
          values: [
            { year: 2021, value: 5.63, score: 9 },
            { year: 2022, value: 6.21, score: 10 },
            { year: 2023, value: 6.85, score: 12 },
          ],
          weight: 10,
          averageScore: 10.33,
        },
        {
          name: 'Current Ratio',
          formula: 'Current Assets / Current Liabilities',
          values: [
            { year: 2021, value: 1.32, score: 10 },
            { year: 2022, value: 1.34, score: 10 },
            { year: 2023, value: 1.36, score: 10 },
          ],
          weight: 10,
          averageScore: 10.0,
        },
        {
          name: 'Cash Ratio',
          formula: 'Cash & Cash Equivalents / Current Liabilities',
          values: [
            { year: 2021, value: 0.45, score: 8 },
            { year: 2022, value: 0.52, score: 10 },
            { year: 2023, value: 0.58, score: 10 },
          ],
          weight: 5,
          averageScore: 9.33,
        },
        {
          name: 'Collection Period (Hari)',
          formula: 'Receivables / Revenue x 365',
          values: [
            { year: 2021, value: 42, score: 10 },
            { year: 2022, value: 38, score: 10 },
            { year: 2023, value: 35, score: 10 },
          ],
          weight: 5,
          averageScore: 10.0,
        },
        {
          name: 'Perputaran Persediaan (Hari)',
          formula: 'Inventory / Revenue x 365',
          values: [
            { year: 2021, value: 18, score: 10 },
            { year: 2022, value: 16, score: 10 },
            { year: 2023, value: 15, score: 10 },
          ],
          weight: 5,
          averageScore: 10.0,
        },
        {
          name: 'Total Asset Turnover (TATO)',
          formula: 'Revenue / Total Assets',
          values: [
            { year: 2021, value: 0.38, score: 6 },
            { year: 2022, value: 0.43, score: 8 },
            { year: 2023, value: 0.43, score: 8 },
          ],
          weight: 5,
          averageScore: 7.33,
        },
        {
          name: 'Debt to Equity Ratio (DER)',
          formula: 'Total Liabilities / Total Equity',
          values: [
            { year: 2021, value: 0.98, score: 17 },
            { year: 2022, value: 0.95, score: 17 },
            { year: 2023, value: 0.92, score: 20 },
          ],
          weight: 20,
          averageScore: 18.0,
        },
      ],
      totalScore: 90.0,
      grade: 'AA',
    },
    legal: {
      aspects: [
        { name: 'Legalitas Badan Usaha', status: 'Lulus', notes: 'Akta pendirian dan perubahan terakhir lengkap dan sah' },
        { name: 'Perizinan Usaha', status: 'Lulus', notes: 'SIUP, NIB, dan izin operasional lengkap dan masih berlaku' },
        { name: 'Kepatuhan Perpajakan', status: 'Lulus', notes: 'NPWP aktif, SPT tahunan terkini telah dilaporkan' },
        { name: 'Riwayat Hukum', status: 'Lulus', notes: 'Tidak memiliki catatan perkara hukum yang material' },
        { name: 'Kepatuhan Regulasi Sektoral', status: 'Lulus', notes: 'Memenuhi seluruh regulasi sektor energi dari BPH Migas' },
        { name: 'Sanksi & Blacklist', status: 'Lulus', notes: 'Tidak tercatat dalam daftar hitam LKPP maupun instansi lain' },
        { name: 'Kepemilikan & Afiliasi', status: 'Lulus', notes: 'Struktur kepemilikan transparan, tidak ada konflik kepentingan' },
      ],
      overallStatus: 'Lulus',
      notaDinas: 'ND-LGL/001/2025 - Hasil Evaluasi Legal PGN untuk Proyek PLTU Mulut Tambang',
    },
    risk: {
      risks: [
        {
          id: 'R1',
          riskCategory: 'proyek',
          category: 'Operasional',
          description: 'Keterlambatan pengiriman peralatan utama dari supplier',
          causes: ['Gangguan rantai pasok global', 'Keterlambatan proses customs', 'Kapasitas supplier tidak memadai'],
          impactDescription: 'Mundurnya jadwal konstruksi, potensi penalti kontrak, dan peningkatan biaya overhead',
          inherentProbability: 3,
          inherentImpact: 4,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Probabilitas sedang karena ketergantungan pada supplier luar negeri. Dampak tinggi karena peralatan utama berada di jalur kritis proyek.',
          mitigations: ['Identifikasi supplier alternatif', 'Kontrak dengan penalty clause', 'Buffer waktu dalam timeline proyek'],
          residualProbability: 2,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Setelah mitigasi, probabilitas turun karena tersedia supplier cadangan. Dampak tetap signifikan namun dapat dikelola dengan buffer waktu.',
        },
        {
          id: 'R2',
          riskCategory: 'mitra',
          category: 'Keuangan',
          description: 'Fluktuasi nilai tukar mempengaruhi biaya impor komponen',
          causes: ['Ketidakstabilan ekonomi global', 'Kebijakan moneter yang berubah', 'Ketergantungan komponen impor yang tinggi'],
          impactDescription: 'Peningkatan biaya proyek hingga 15-20%, tekanan pada margin keuntungan mitra, potensi renegosiasi kontrak',
          inherentProbability: 4,
          inherentImpact: 3,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Probabilitas tinggi mengingat volatilitas kurs USD/IDR. Dampak sedang karena komponen impor mencapai 40% dari total biaya.',
          mitigations: ['Hedging mata uang asing', 'Diversifikasi supplier lokal dan internasional'],
          residualProbability: 2,
          residualImpact: 2,
          residualLevel: 'Rendah',
          justifikasiResidual: 'Hedging valuta asing secara signifikan mengurangi eksposur. Diversifikasi supplier mengurangi ketergantungan impor.',
        },
        {
          id: 'R3',
          riskCategory: 'proyek',
          category: 'Lingkungan',
          description: 'Potensi pencemaran udara dari operasional PLTU',
          causes: ['Pembakaran batubara menghasilkan SO₂ dan NOx', 'Potensi fly ash dan bottom ash', 'Regulasi emisi yang semakin ketat'],
          impactDescription: 'Sanksi regulasi, gangguan kesehatan masyarakat sekitar, risiko pencabutan izin operasi',
          inherentProbability: 3,
          inherentImpact: 5,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Probabilitas sedang karena teknologi PLTU modern. Dampak sangat tinggi karena potensi dampak kesehatan dan sanksi hukum.',
          mitigations: ['Instalasi FGD (Flue Gas Desulfurization)', 'Monitoring emisi berkala', 'Kepatuhan standar emisi KLHK'],
          residualProbability: 1,
          residualImpact: 3,
          residualLevel: 'Rendah',
          justifikasiResidual: 'FGD mengurangi emisi SO₂ hingga 90%. Monitoring berkala memastikan kepatuhan regulasi secara berkelanjutan.',
        },
        {
          id: 'R4',
          riskCategory: 'proyek',
          category: 'Reputasi',
          description: 'Resistensi masyarakat terhadap pembangunan PLTU baru',
          causes: ['Kekhawatiran dampak lingkungan', 'Kurangnya sosialisasi awal', 'Isu pembebasan lahan'],
          impactDescription: 'Penundaan konstruksi, peningkatan biaya legal dan sosial, risiko penghentian proyek',
          inherentProbability: 3,
          inherentImpact: 3,
          inherentLevel: 'Sedang',
          justifikasiInheren: 'Probabilitas dan dampak sama-sama sedang. Tren global anti-batubara meningkatkan sensitivitas publik.',
          mitigations: ['Program sosialisasi dan community engagement', 'Program CSR berkelanjutan', 'Transparansi informasi proyek'],
          residualProbability: 2,
          residualImpact: 2,
          residualLevel: 'Rendah',
          justifikasiResidual: 'Engagement aktif dengan masyarakat dan program CSR yang terstruktur efektif meredam resistensi.',
        },
      ],
      overallLevel: 'Sedang',
      conclusion: 'Catatan',
      notaDinasNumber: 'ND-RSK/001/2025',
    },
    totalScore: 88.5,
    grade: 'A',
    status: 'Selesai',
    evaluatedBy: 'U006',
    evaluatedAt: '2025-10-15T14:30:00Z',
  },
  {
    id: 'EVAL-002',
    projectId: 'P001',
    partnerId: 'M004',
    partnerName: 'PT Medco Energi Internasional Tbk',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 4.50, weight: 0.30, notes: 'INALUM merupakan holding industri pertambangan terbesar di Indonesia' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 4.00, weight: 0.25, notes: 'Industri pertambangan dan metal menghadapi tantangan transisi energi' },
        { name: 'Reputasi & Brand Value', score: 4.50, weight: 0.25, notes: 'Reputasi kuat sebagai BUMN strategis holding industri pertambangan' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 4.00, weight: 0.20, notes: 'Jaringan distribusi aluminium dan komoditas yang luas' },
      ],
      total: 4.28,
      weight: 0.15,
      weightedScore: 0.642,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 4.00, weight: 0.30, notes: 'Memiliki kapabilitas pengolahan mineral dan metalurgi tinggi' },
        { name: 'Pengalaman Proyek Sejenis', score: 3.50, weight: 0.25, notes: 'Pengalaman terbatas dalam proyek gasifikasi batubara' },
        { name: 'Sumber Daya Manusia Teknis', score: 4.00, weight: 0.25, notes: 'Tenaga ahli pertambangan dan metalurgi berkualitas' },
        { name: 'Fasilitas & Peralatan', score: 4.50, weight: 0.20, notes: 'Fasilitas smelter dan pengolahan skala besar' },
      ],
      total: 4.00,
      weight: 0.20,
      weightedScore: 0.80,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 3.50, weight: 0.40, notes: 'Tantangan lingkungan dari operasi smelter, upaya perbaikan berkelanjutan' },
        { name: 'Social (Sosial)', score: 4.00, weight: 0.30, notes: 'Program pemberdayaan masyarakat sekitar operasi cukup aktif' },
        { name: 'Governance (Tata Kelola)', score: 4.00, weight: 0.30, notes: 'Tata kelola BUMN holding yang memadai, sedang perbaikan berkelanjutan' },
      ],
      total: 3.80,
      weight: 0.10,
      weightedScore: 0.38,
    },
    financial: {
      indicators: [
        {
          name: 'Return on Equity (ROE)',
          formula: 'Net Income / Total Equity x 100%',
          values: [
            { year: 2021, value: 10.24, score: 15 },
            { year: 2022, value: 10.85, score: 15 },
            { year: 2023, value: 8.83, score: 14 },
          ],
          weight: 15,
          averageScore: 14.67,
        },
        {
          name: 'Return on Investment (ROI)',
          formula: 'EBIT / Total Assets x 100%',
          values: [
            { year: 2021, value: 7.10, score: 12 },
            { year: 2022, value: 7.56, score: 12 },
            { year: 2023, value: 6.38, score: 10 },
          ],
          weight: 10,
          averageScore: 11.33,
        },
        {
          name: 'Current Ratio',
          formula: 'Current Assets / Current Liabilities',
          values: [
            { year: 2021, value: 1.52, score: 10 },
            { year: 2022, value: 1.50, score: 10 },
            { year: 2023, value: 1.48, score: 10 },
          ],
          weight: 10,
          averageScore: 10.0,
        },
        {
          name: 'Cash Ratio',
          formula: 'Cash & Cash Equivalents / Current Liabilities',
          values: [
            { year: 2021, value: 0.38, score: 6 },
            { year: 2022, value: 0.42, score: 8 },
            { year: 2023, value: 0.35, score: 6 },
          ],
          weight: 5,
          averageScore: 6.67,
        },
        {
          name: 'Collection Period (Hari)',
          formula: 'Receivables / Revenue x 365',
          values: [
            { year: 2021, value: 55, score: 8 },
            { year: 2022, value: 50, score: 8 },
            { year: 2023, value: 52, score: 8 },
          ],
          weight: 5,
          averageScore: 8.0,
        },
        {
          name: 'Perputaran Persediaan (Hari)',
          formula: 'Inventory / Revenue x 365',
          values: [
            { year: 2021, value: 45, score: 6 },
            { year: 2022, value: 42, score: 8 },
            { year: 2023, value: 48, score: 6 },
          ],
          weight: 5,
          averageScore: 6.67,
        },
        {
          name: 'Total Asset Turnover (TATO)',
          formula: 'Revenue / Total Assets',
          values: [
            { year: 2021, value: 0.29, score: 4 },
            { year: 2022, value: 0.30, score: 4 },
            { year: 2023, value: 0.26, score: 4 },
          ],
          weight: 5,
          averageScore: 4.0,
        },
        {
          name: 'Debt to Equity Ratio (DER)',
          formula: 'Total Liabilities / Total Equity',
          values: [
            { year: 2021, value: 0.87, score: 20 },
            { year: 2022, value: 0.83, score: 20 },
            { year: 2023, value: 0.80, score: 20 },
          ],
          weight: 20,
          averageScore: 20.0,
        },
      ],
      totalScore: 77.90,
      grade: 'A',
    },
    legal: {
      aspects: [
        { name: 'Legalitas Badan Usaha', status: 'Lulus', notes: 'Akta pendirian dan perubahan terkini sah dan valid' },
        { name: 'Perizinan Usaha', status: 'Lulus', notes: 'Seluruh perizinan pertambangan dan usaha lengkap' },
        { name: 'Kepatuhan Perpajakan', status: 'Lulus', notes: 'Kepatuhan perpajakan BUMN holding terpenuhi' },
        { name: 'Riwayat Hukum', status: 'Bersyarat', notes: 'Terdapat beberapa sengketa pertanahan yang sedang diselesaikan' },
        { name: 'Kepatuhan Regulasi Sektoral', status: 'Lulus', notes: 'Memenuhi regulasi pertambangan dari Kementerian ESDM' },
        { name: 'Sanksi & Blacklist', status: 'Lulus', notes: 'Tidak tercatat dalam daftar hitam instansi manapun' },
        { name: 'Kepemilikan & Afiliasi', status: 'Lulus', notes: 'BUMN dengan kepemilikan pemerintah 100%, transparan' },
      ],
      overallStatus: 'Bersyarat',
      notaDinas: 'ND-LGL/005/2025 - Hasil Evaluasi Legal INALUM untuk Proyek Gasifikasi',
    },
    risk: {
      risks: [
        {
          id: 'R1',
          riskCategory: 'proyek',
          category: 'Strategis',
          description: 'Perubahan kebijakan pemerintah terkait hilirisasi mineral dan batubara',
          causes: ['Dinamika politik nasional', 'Tekanan internasional terhadap industri batubara', 'Perubahan prioritas energi nasional'],
          impactDescription: 'Ketidakpastian arah proyek, potensi perubahan skema bisnis fundamental, penundaan investasi',
          inherentProbability: 3,
          inherentImpact: 5,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Probabilitas sedang karena tren kebijakan hilirisasi yang belum menentu. Dampak sangat tinggi karena fundamental bisnis terpengaruh.',
          mitigations: ['Lobby dan advokasi kebijakan', 'Monitoring regulasi berkala', 'Diversifikasi model bisnis'],
          residualProbability: 2,
          residualImpact: 4,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Monitoring aktif dan diversifikasi model bisnis mengurangi eksposur, namun risiko regulasi tidak dapat sepenuhnya dieliminasi.',
        },
        {
          id: 'R2',
          riskCategory: 'proyek',
          category: 'Operasional',
          description: 'Kegagalan integrasi teknologi gasifikasi dengan infrastruktur existing',
          causes: ['Kompleksitas teknologi gasifikasi yang baru', 'Perbedaan standar teknis infrastruktur lama dan baru', 'Keterbatasan tenaga ahli teknologi gasifikasi'],
          impactDescription: 'Penundaan operasional, biaya perbaikan tinggi, potensi kerugian produksi jangka panjang',
          inherentProbability: 3,
          inherentImpact: 4,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Teknologi gasifikasi relatif baru di Indonesia meningkatkan risiko teknis. Dampak tinggi karena integrasi berada di jalur kritis proyek.',
          mitigations: ['Studi kelayakan mendalam', 'Pilot project sebelum full-scale', 'Konsultan teknologi internasional'],
          residualProbability: 2,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Pilot project secara signifikan mengurangi risiko teknis. Konsultan internasional memastikan standar teknis terpenuhi.',
        },
        {
          id: 'R3',
          riskCategory: 'mitra',
          category: 'Keuangan',
          description: 'Penurunan harga komoditas aluminium dan batubara',
          causes: ['Perlambatan ekonomi global', 'Oversupply komoditas di pasar internasional', 'Pergeseran ke energi terbarukan'],
          impactDescription: 'Penurunan revenue mitra, tekanan likuiditas, potensi kesulitan pembayaran kewajiban kontrak',
          inherentProbability: 4,
          inherentImpact: 4,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Harga komoditas sangat volatil dan sering turun di luar kendali mitra. Dampak langsung ke kemampuan finansial mitra.',
          mitigations: ['Hedging komoditas', 'Kontrak jangka panjang dengan off-taker', 'Struktur pembiayaan yang fleksibel'],
          residualProbability: 3,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Hedging dan kontrak off-taker jangka panjang mengurangi eksposur, namun risiko pasar komoditas tidak dapat dieliminasi sepenuhnya.',
        },
        {
          id: 'R4',
          riskCategory: 'proyek',
          category: 'Lingkungan',
          description: 'Dampak lingkungan dari proses gasifikasi dan pengolahan',
          causes: ['Emisi gas berbahaya dari proses gasifikasi', 'Limbah cair dan padat pengolahan', 'Potensi kontaminasi air tanah'],
          impactDescription: 'Sanksi KLHK, penghentian operasi, biaya remediasi lingkungan yang tinggi',
          inherentProbability: 3,
          inherentImpact: 5,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Proses gasifikasi menghasilkan berbagai emisi. Dampak sangat tinggi karena potensi kerusakan lingkungan jangka panjang.',
          mitigations: ['Teknologi carbon capture', 'Monitoring emisi real-time', 'Compliance AMDAL ketat'],
          residualProbability: 2,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Carbon capture dan monitoring real-time secara signifikan mengurangi dampak. AMDAL memastikan kepatuhan regulasi.',
        },
        {
          id: 'R5',
          riskCategory: 'proyek',
          category: 'Hukum',
          description: 'Sengketa lahan dan perizinan dengan masyarakat setempat',
          causes: ['Tumpang tindih klaim lahan', 'Proses sosialisasi yang tidak memadai', 'Kompensasi yang dianggap tidak adil'],
          impactDescription: 'Penghentian konstruksi oleh pengadilan, biaya hukum tinggi, kerusakan reputasi',
          inherentProbability: 3,
          inherentImpact: 3,
          inherentLevel: 'Sedang',
          justifikasiInheren: 'Sengketa lahan umum terjadi di proyek skala besar. Dampak sedang karena dapat diselesaikan melalui jalur hukum.',
          mitigations: ['Penyelesaian sengketa lahan proaktif', 'Konsultasi publik berkala', 'Kompensasi yang adil'],
          residualProbability: 2,
          residualImpact: 2,
          residualLevel: 'Rendah',
          justifikasiResidual: 'Pendekatan proaktif dan kompensasi yang adil efektif menyelesaikan sengketa sebelum eskalasi hukum.',
        },
      ],
      overallLevel: 'Sedang',
      conclusion: 'Catatan',
      notaDinasNumber: 'ND-RSK/002/2025',
    },
    totalScore: 80.2,
    grade: 'A',
    status: 'Selesai',
    evaluatedBy: 'U006',
    evaluatedAt: '2025-09-20T10:15:00Z',
  },
  {
    id: 'EVAL-003',
    projectId: 'P002',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 4.00, weight: 0.30, notes: 'Posisi kuat di sektor minyak dan gas bumi Indonesia' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 4.50, weight: 0.25, notes: 'Sektor energi menunjukkan pertumbuhan positif dengan diversifikasi portofolio' },
        { name: 'Reputasi & Brand Value', score: 4.50, weight: 0.25, notes: 'Reputasi baik sebagai perusahaan energi terintegrasi swasta terbesar' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 3.50, weight: 0.20, notes: 'Jaringan pemasaran cukup luas di sektor energi konvensional' },
      ],
      total: 4.15,
      weight: 0.15,
      weightedScore: 0.6225,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 4.50, weight: 0.30, notes: 'Pengalaman operasional pembangkit listrik termasuk geothermal' },
        { name: 'Pengalaman Proyek Sejenis', score: 4.50, weight: 0.25, notes: 'Mengoperasikan PLTU dan pembangkit listrik lainnya' },
        { name: 'Sumber Daya Manusia Teknis', score: 4.00, weight: 0.25, notes: 'SDM teknis berkualitas dengan sertifikasi internasional' },
        { name: 'Fasilitas & Peralatan', score: 4.00, weight: 0.20, notes: 'Fasilitas pembangkit dan peralatan EPC yang memadai' },
      ],
      total: 4.30,
      weight: 0.20,
      weightedScore: 0.86,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 4.50, weight: 0.40, notes: 'Komitmen kuat terhadap energi terbarukan melalui Medco Power' },
        { name: 'Social (Sosial)', score: 4.00, weight: 0.30, notes: 'Program CSR dan pemberdayaan masyarakat berjalan baik' },
        { name: 'Governance (Tata Kelola)', score: 4.00, weight: 0.30, notes: 'Tata kelola perusahaan publik yang baik dan transparan' },
      ],
      total: 4.20,
      weight: 0.10,
      weightedScore: 0.42,
    },
    financial: {
      indicators: [
        {
          name: 'Return on Equity (ROE)',
          formula: 'Net Income / Total Equity x 100%',
          values: [
            { year: 2021, value: 10.29, score: 15 },
            { year: 2022, value: 14.71, score: 18 },
            { year: 2023, value: 11.34, score: 15 },
          ],
          weight: 15,
          averageScore: 16.0,
        },
        {
          name: 'Return on Investment (ROI)',
          formula: 'EBIT / Total Assets x 100%',
          values: [
            { year: 2021, value: 6.12, score: 10 },
            { year: 2022, value: 8.88, score: 14 },
            { year: 2023, value: 7.15, score: 12 },
          ],
          weight: 10,
          averageScore: 12.0,
        },
        {
          name: 'Current Ratio',
          formula: 'Current Assets / Current Liabilities',
          values: [
            { year: 2021, value: 1.27, score: 10 },
            { year: 2022, value: 1.32, score: 10 },
            { year: 2023, value: 1.34, score: 10 },
          ],
          weight: 10,
          averageScore: 10.0,
        },
        {
          name: 'Cash Ratio',
          formula: 'Cash & Cash Equivalents / Current Liabilities',
          values: [
            { year: 2021, value: 0.35, score: 6 },
            { year: 2022, value: 0.41, score: 8 },
            { year: 2023, value: 0.44, score: 8 },
          ],
          weight: 5,
          averageScore: 7.33,
        },
        {
          name: 'Collection Period (Hari)',
          formula: 'Receivables / Revenue x 365',
          values: [
            { year: 2021, value: 65, score: 6 },
            { year: 2022, value: 58, score: 8 },
            { year: 2023, value: 55, score: 8 },
          ],
          weight: 5,
          averageScore: 7.33,
        },
        {
          name: 'Perputaran Persediaan (Hari)',
          formula: 'Inventory / Revenue x 365',
          values: [
            { year: 2021, value: 28, score: 8 },
            { year: 2022, value: 25, score: 10 },
            { year: 2023, value: 22, score: 10 },
          ],
          weight: 5,
          averageScore: 9.33,
        },
        {
          name: 'Total Asset Turnover (TATO)',
          formula: 'Revenue / Total Assets',
          values: [
            { year: 2021, value: 0.29, score: 4 },
            { year: 2022, value: 0.36, score: 6 },
            { year: 2023, value: 0.36, score: 6 },
          ],
          weight: 5,
          averageScore: 5.33,
        },
        {
          name: 'Debt to Equity Ratio (DER)',
          formula: 'Total Liabilities / Total Equity',
          values: [
            { year: 2021, value: 1.40, score: 12 },
            { year: 2022, value: 1.36, score: 12 },
            { year: 2023, value: 1.28, score: 15 },
          ],
          weight: 20,
          averageScore: 13.0,
        },
      ],
      totalScore: 82.32,
      grade: 'AA',
    },
    status: 'Draft',
    evaluatedBy: 'U002',
    evaluatedAt: '2025-10-18T16:45:00Z',
  },
  {
    id: 'EVAL-004',
    projectId: 'P003',
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 4.00, weight: 0.30, notes: 'Sub-holding Pertamina dengan fokus energi baru terbarukan, posisi strategis' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 5.00, weight: 0.25, notes: 'Sektor EBT tumbuh pesat, dukungan kuat dari kebijakan pemerintah' },
        { name: 'Reputasi & Brand Value', score: 4.50, weight: 0.25, notes: 'Didukung brand Pertamina yang sangat kuat di sektor energi' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 3.50, weight: 0.20, notes: 'Jaringan masih dalam tahap pengembangan untuk produk EBT' },
      ],
      total: 4.28,
      weight: 0.15,
      weightedScore: 0.642,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 3.50, weight: 0.30, notes: 'Kapabilitas teknologi EBT sedang dikembangkan, akses ke teknologi Pertamina group' },
        { name: 'Pengalaman Proyek Sejenis', score: 3.00, weight: 0.25, notes: 'Pengalaman terbatas sebagai entitas baru, leverage dari Pertamina induk' },
        { name: 'Sumber Daya Manusia Teknis', score: 3.50, weight: 0.25, notes: 'SDM teknis berkualitas namun jumlah masih terbatas' },
        { name: 'Fasilitas & Peralatan', score: 3.00, weight: 0.20, notes: 'Fasilitas masih dalam pengembangan, memanfaatkan fasilitas Pertamina group' },
      ],
      total: 3.28,
      weight: 0.20,
      weightedScore: 0.656,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 5.00, weight: 0.40, notes: 'Fokus bisnis pada energi terbarukan, rating ESG sangat tinggi' },
        { name: 'Social (Sosial)', score: 4.00, weight: 0.30, notes: 'Program sosial memanfaatkan platform Pertamina group' },
        { name: 'Governance (Tata Kelola)', score: 3.50, weight: 0.30, notes: 'Tata kelola sub-holding baru, masih dalam pembenahan' },
      ],
      total: 4.25,
      weight: 0.10,
      weightedScore: 0.425,
    },
    financial: {
      indicators: [
        {
          name: 'Return on Equity (ROE)',
          formula: 'Net Income / Total Equity x 100%',
          values: [
            { year: 2021, value: 6.72, score: 10 },
            { year: 2022, value: 8.37, score: 12 },
            { year: 2023, value: 9.16, score: 14 },
          ],
          weight: 15,
          averageScore: 12.0,
        },
        {
          name: 'Return on Investment (ROI)',
          formula: 'EBIT / Total Assets x 100%',
          values: [
            { year: 2021, value: 4.80, score: 8 },
            { year: 2022, value: 5.70, score: 9 },
            { year: 2023, value: 6.25, score: 10 },
          ],
          weight: 10,
          averageScore: 9.0,
        },
        {
          name: 'Current Ratio',
          formula: 'Current Assets / Current Liabilities',
          values: [
            { year: 2021, value: 1.61, score: 10 },
            { year: 2022, value: 1.60, score: 10 },
            { year: 2023, value: 1.76, score: 10 },
          ],
          weight: 10,
          averageScore: 10.0,
        },
        {
          name: 'Cash Ratio',
          formula: 'Cash & Cash Equivalents / Current Liabilities',
          values: [
            { year: 2021, value: 0.55, score: 10 },
            { year: 2022, value: 0.60, score: 10 },
            { year: 2023, value: 0.65, score: 10 },
          ],
          weight: 5,
          averageScore: 10.0,
        },
        {
          name: 'Collection Period (Hari)',
          formula: 'Receivables / Revenue x 365',
          values: [
            { year: 2021, value: 72, score: 4 },
            { year: 2022, value: 65, score: 6 },
            { year: 2023, value: 58, score: 8 },
          ],
          weight: 5,
          averageScore: 6.0,
        },
        {
          name: 'Perputaran Persediaan (Hari)',
          formula: 'Inventory / Revenue x 365',
          values: [
            { year: 2021, value: 15, score: 10 },
            { year: 2022, value: 12, score: 10 },
            { year: 2023, value: 10, score: 10 },
          ],
          weight: 5,
          averageScore: 10.0,
        },
        {
          name: 'Total Asset Turnover (TATO)',
          formula: 'Revenue / Total Assets',
          values: [
            { year: 2021, value: 0.26, score: 4 },
            { year: 2022, value: 0.30, score: 4 },
            { year: 2023, value: 0.34, score: 6 },
          ],
          weight: 5,
          averageScore: 4.67,
        },
        {
          name: 'Debt to Equity Ratio (DER)',
          formula: 'Total Liabilities / Total Equity',
          values: [
            { year: 2021, value: 0.87, score: 20 },
            { year: 2022, value: 0.84, score: 20 },
            { year: 2023, value: 0.79, score: 20 },
          ],
          weight: 20,
          averageScore: 20.0,
        },
      ],
      totalScore: 73.17,
      grade: 'BBB',
    },
    legal: {
      aspects: [
        { name: 'Legalitas Badan Usaha', status: 'Lulus', notes: 'Akta pendirian sub-holding sah dan valid' },
        { name: 'Perizinan Usaha', status: 'Bersyarat', notes: 'Beberapa izin operasional EBT masih dalam proses' },
        { name: 'Kepatuhan Perpajakan', status: 'Lulus', notes: 'Kepatuhan pajak terpenuhi melalui group Pertamina' },
        { name: 'Riwayat Hukum', status: 'Lulus', notes: 'Tidak ada catatan hukum sebagai entitas baru' },
        { name: 'Kepatuhan Regulasi Sektoral', status: 'Bersyarat', notes: 'Proses pengurusan izin IUPTL untuk beberapa proyek EBT' },
        { name: 'Sanksi & Blacklist', status: 'Lulus', notes: 'Tidak tercatat dalam daftar hitam' },
        { name: 'Kepemilikan & Afiliasi', status: 'Lulus', notes: 'Sub-holding Pertamina, kepemilikan BUMN transparan' },
      ],
      overallStatus: 'Bersyarat',
      notaDinas: 'ND-LGL/008/2025 - Hasil Evaluasi Legal PNRE untuk Proyek Gasifikasi',
    },
    risk: {
      risks: [
        {
          id: 'R1',
          riskCategory: 'mitra',
          category: 'Strategis',
          description: 'Ketidakpastian arah bisnis sub-holding baru dalam ekosistem Pertamina',
          causes: ['Status sebagai entitas baru yang belum mapan', 'Potensi perubahan arah holding Pertamina', 'Tumpang tindih mandate dengan entitas Pertamina lain'],
          impactDescription: 'Ketidakstabilan manajemen, perubahan kebijakan mendadak, potensi perubahan komitmen terhadap proyek',
          inherentProbability: 3,
          inherentImpact: 4,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Sebagai sub-holding baru, risiko korporat lebih tinggi. Dampak tinggi karena keputusan holding dapat mempengaruhi kapasitas mitra.',
          mitigations: ['MoU strategis dengan Pertamina induk', 'Roadmap bisnis 5 tahun yang jelas', 'Dukungan pendanaan dari holding'],
          residualProbability: 2,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'MoU dengan induk memberikan kepastian. Roadmap yang clear mengurangi ambiguitas arah bisnis.',
        },
        {
          id: 'R2',
          riskCategory: 'mitra',
          category: 'Teknis',
          description: 'Keterbatasan pengalaman dalam proyek gasifikasi batubara',
          causes: ['Track record terbatas di sektor gasifikasi', 'SDM teknis yang belum terbangun', 'Teknologi gasifikasi yang kompleks dan spesifik'],
          impactDescription: 'Kualitas eksekusi proyek rendah, potensi kegagalan teknis, biaya pembelajaran yang mahal',
          inherentProbability: 4,
          inherentImpact: 4,
          inherentLevel: 'Tinggi',
          justifikasiInheren: 'Probabilitas tinggi karena track record terbatas di gasifikasi. Dampak tinggi karena kegagalan teknis langsung berdampak pada proyek.',
          mitigations: ['Partnership dengan technology provider internasional', 'Training dan transfer knowledge', 'Pilot project skala kecil terlebih dahulu'],
          residualProbability: 3,
          residualImpact: 3,
          residualLevel: 'Sedang',
          justifikasiResidual: 'Partnership dengan provider internasional menambah kapabilitas. Namun risiko residual tetap sedang karena learning curve yang diperlukan.',
        },
        {
          id: 'R3',
          riskCategory: 'mitra',
          category: 'Keuangan',
          description: 'Ketergantungan pendanaan dari Pertamina holding',
          causes: ['Belum memiliki revenue mandiri yang signifikan', 'Akses pasar modal yang terbatas sebagai entitas baru', 'Prioritas pendanaan holding yang dapat berubah'],
          impactDescription: 'Keterlambatan pembayaran kontraktor, gangguan cashflow proyek, potensi penghentian sementara proyek',
          inherentProbability: 3,
          inherentImpact: 3,
          inherentLevel: 'Sedang',
          justifikasiInheren: 'Ketergantungan pada holding cukup umum untuk sub-holding baru. Dampak sedang karena Pertamina memiliki kapasitas keuangan yang kuat.',
          mitigations: ['Diversifikasi sumber pendanaan', 'Kerjasama pembiayaan dengan lembaga internasional', 'Target kemandirian keuangan bertahap'],
          residualProbability: 2,
          residualImpact: 2,
          residualLevel: 'Rendah',
          justifikasiResidual: 'Diversifikasi pendanaan dan kerjasama internasional mengurangi ketergantungan. Target kemandirian bertahap memberikan arah yang jelas.',
        },
      ],
      overallLevel: 'Sedang',
      conclusion: 'Catatan',
      notaDinasNumber: 'ND-RSK/004/2025',
    },
    totalScore: 74.3,
    grade: 'BBB',
    status: 'Draft',
    evaluatedBy: 'U010',
    evaluatedAt: '2025-11-05T09:20:00Z',
  },
  {
    id: 'EVAL-005',
    projectId: 'P002',
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 3.50, weight: 0.30, notes: 'PNRE masih membangun posisi pasar di sektor gasifikasi, namun didukung ekosistem Pertamina' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 4.50, weight: 0.25, notes: 'Tren gasifikasi batubara meningkat sejalan dengan kebijakan hilirisasi nasional' },
        { name: 'Reputasi & Brand Value', score: 4.00, weight: 0.25, notes: 'Reputasi kuat sebagai bagian dari Pertamina Group' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 3.00, weight: 0.20, notes: 'Jaringan distribusi untuk produk gasifikasi masih terbatas' },
      ],
      total: 3.78,
      weight: 0.15,
      weightedScore: 0.567,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 3.50, weight: 0.30, notes: 'Akses teknologi dari Pertamina Group dan kemitraan internasional' },
        { name: 'Pengalaman Proyek Sejenis', score: 2.50, weight: 0.25, notes: 'Pengalaman langsung di gasifikasi batubara masih minim' },
        { name: 'Sumber Daya Manusia Teknis', score: 3.50, weight: 0.25, notes: 'SDM teknis berkualitas namun perlu penambahan spesialis gasifikasi' },
        { name: 'Fasilitas & Peralatan', score: 3.00, weight: 0.20, notes: 'Fasilitas pilot plant dalam tahap pembangunan' },
      ],
      total: 3.18,
      weight: 0.20,
      weightedScore: 0.636,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 4.50, weight: 0.40, notes: 'Komitmen kuat terhadap energi bersih dan pengurangan emisi karbon' },
        { name: 'Social (Sosial)', score: 4.00, weight: 0.30, notes: 'Program CSR terintegrasi dengan Pertamina Group' },
        { name: 'Governance (Tata Kelola)', score: 3.50, weight: 0.30, notes: 'Tata kelola sub-holding masih dalam penyempurnaan' },
      ],
      total: 4.05,
      weight: 0.10,
      weightedScore: 0.405,
    },
    status: 'Draft',
    evaluatedBy: 'U006',
    evaluatedAt: '2025-10-28T11:30:00Z',
  },
  {
    id: 'EVAL-006',
    projectId: 'P002',
    partnerId: 'M005',
    partnerName: 'PT Indonesia Asahan Aluminium (INALUM)',
    phase: 'phase2',
    market: {
      subScores: [
        { name: 'Pangsa Pasar & Posisi Kompetitif', score: 4.50, weight: 0.30, notes: 'INALUM sebagai holding BUMN pertambangan memiliki posisi dominan di sektor hilirisasi mineral' },
        { name: 'Pertumbuhan Industri & Tren Pasar', score: 4.00, weight: 0.25, notes: 'Industri hilirisasi batubara mendapat dukungan kebijakan pemerintah' },
        { name: 'Reputasi & Brand Value', score: 4.50, weight: 0.25, notes: 'Reputasi sangat kuat sebagai BUMN holding industri pertambangan strategis' },
        { name: 'Jaringan Distribusi & Pemasaran', score: 4.00, weight: 0.20, notes: 'Jaringan distribusi luas melalui anak perusahaan dan afiliasi' },
      ],
      total: 4.28,
      weight: 0.15,
      weightedScore: 0.642,
    },
    technical: {
      subScores: [
        { name: 'Kapabilitas Teknis & Teknologi', score: 4.00, weight: 0.30, notes: 'Kapabilitas pengolahan mineral dan metalurgi tinggi, relevan dengan gasifikasi' },
        { name: 'Pengalaman Proyek Sejenis', score: 3.50, weight: 0.25, notes: 'Pengalaman terbatas di gasifikasi namun kuat di proyek hilirisasi skala besar' },
        { name: 'Sumber Daya Manusia Teknis', score: 4.00, weight: 0.25, notes: 'Tenaga ahli pertambangan dan pengolahan berkualitas internasional' },
        { name: 'Fasilitas & Peralatan', score: 4.50, weight: 0.20, notes: 'Fasilitas smelter dan pengolahan skala besar yang dapat diadaptasi' },
      ],
      total: 4.00,
      weight: 0.20,
      weightedScore: 0.80,
    },
    esg: {
      subScores: [
        { name: 'Environmental (Lingkungan)', score: 3.50, weight: 0.40, notes: 'Tantangan lingkungan dari operasi smelter, sedang dalam transisi ke green smelting' },
        { name: 'Social (Sosial)', score: 4.00, weight: 0.30, notes: 'Program pemberdayaan masyarakat sekitar operasi berjalan aktif dan konsisten' },
        { name: 'Governance (Tata Kelola)', score: 4.00, weight: 0.30, notes: 'Tata kelola BUMN holding yang terstruktur dan memenuhi standar OJK' },
      ],
      total: 3.80,
      weight: 0.10,
      weightedScore: 0.38,
    },
    financial: {
      indicators: [
        {
          name: 'Return on Equity (ROE)',
          formula: 'Net Income / Total Equity x 100%',
          values: [
            { year: 2021, value: 10.24, score: 15 },
            { year: 2022, value: 10.85, score: 15 },
            { year: 2023, value: 8.83, score: 14 },
          ],
          weight: 15,
          averageScore: 14.67,
        },
        {
          name: 'Return on Investment (ROI)',
          formula: 'EBIT / Total Assets x 100%',
          values: [
            { year: 2021, value: 7.10, score: 12 },
            { year: 2022, value: 7.56, score: 12 },
            { year: 2023, value: 6.38, score: 10 },
          ],
          weight: 10,
          averageScore: 11.33,
        },
        {
          name: 'Current Ratio',
          formula: 'Current Assets / Current Liabilities',
          values: [
            { year: 2021, value: 1.52, score: 10 },
            { year: 2022, value: 1.50, score: 10 },
            { year: 2023, value: 1.48, score: 10 },
          ],
          weight: 10,
          averageScore: 10.0,
        },
        {
          name: 'Cash Ratio',
          formula: 'Cash & Cash Equivalents / Current Liabilities',
          values: [
            { year: 2021, value: 0.38, score: 6 },
            { year: 2022, value: 0.42, score: 8 },
            { year: 2023, value: 0.35, score: 6 },
          ],
          weight: 5,
          averageScore: 6.67,
        },
        {
          name: 'Collection Period (Hari)',
          formula: 'Receivables / Revenue x 365',
          values: [
            { year: 2021, value: 55, score: 8 },
            { year: 2022, value: 50, score: 8 },
            { year: 2023, value: 52, score: 8 },
          ],
          weight: 5,
          averageScore: 8.0,
        },
        {
          name: 'Perputaran Persediaan (Hari)',
          formula: 'Inventory / Revenue x 365',
          values: [
            { year: 2021, value: 45, score: 6 },
            { year: 2022, value: 42, score: 8 },
            { year: 2023, value: 48, score: 6 },
          ],
          weight: 5,
          averageScore: 6.67,
        },
        {
          name: 'Total Asset Turnover (TATO)',
          formula: 'Revenue / Total Assets',
          values: [
            { year: 2021, value: 0.29, score: 4 },
            { year: 2022, value: 0.30, score: 4 },
            { year: 2023, value: 0.26, score: 4 },
          ],
          weight: 5,
          averageScore: 4.0,
        },
        {
          name: 'Debt to Equity Ratio (DER)',
          formula: 'Total Liabilities / Total Equity',
          values: [
            { year: 2021, value: 0.87, score: 20 },
            { year: 2022, value: 0.83, score: 20 },
            { year: 2023, value: 0.80, score: 20 },
          ],
          weight: 20,
          averageScore: 20.0,
        },
      ],
      totalScore: 77.90,
      grade: 'A',
    },
    status: 'Draft',
    evaluatedBy: 'U006',
    evaluatedAt: '2025-10-22T14:00:00Z',
  },
  // Fase 1 Evaluations for P001
  {
    id: 'EVAL-P1-001',
    projectId: 'P001',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    phase: 'phase1',
    phase1Eval: {
      partnerId: 'M001',
      partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
      criteria: [
        { name: 'Kualitas Profil Perusahaan', score: 4, maxScore: 5, notes: 'Profil perusahaan sangat lengkap dan profesional' },
        { name: 'Pengalaman Proyek Relevan', score: 5, maxScore: 5, notes: 'Pengalaman luas di sektor energi dan infrastruktur gas' },
        { name: 'Kemampuan Pembiayaan', score: 4, maxScore: 5, notes: 'Kapasitas pendanaan kuat sebagai BUMN besar' },
        { name: 'Gambaran Umum Keuangan', score: 4, maxScore: 5, notes: 'Kondisi keuangan sehat dan stabil' },
        { name: 'Pemenuhan Persyaratan', score: 5, maxScore: 5, notes: 'Semua persyaratan terpenuhi' },
      ],
      overallResult: 'Lolos',
      evaluatedBy: 'U002',
      evaluatedAt: '2025-11-15T10:00:00Z',
      notes: 'Mitra sangat qualified untuk melanjutkan ke Fase 2',
    },
    status: 'Selesai',
    evaluatedBy: 'U002',
    evaluatedAt: '2025-11-15T10:00:00Z',
  },
  {
    id: 'EVAL-P1-002',
    projectId: 'P001',
    partnerId: 'M004',
    partnerName: 'PT Medco Energi Internasional Tbk',
    phase: 'phase1',
    phase1Eval: {
      partnerId: 'M004',
      partnerName: 'PT Medco Energi Internasional Tbk',
      criteria: [
        { name: 'Kualitas Profil Perusahaan', score: 4, maxScore: 5, notes: 'Profil perusahaan baik dan terstruktur' },
        { name: 'Pengalaman Proyek Relevan', score: 4, maxScore: 5, notes: 'Pengalaman cukup di sektor energi, terutama migas' },
        { name: 'Kemampuan Pembiayaan', score: 5, maxScore: 5, notes: 'Kapasitas pembiayaan sangat kuat' },
        { name: 'Gambaran Umum Keuangan', score: 4, maxScore: 5, notes: 'Keuangan sehat dengan revenue besar' },
        { name: 'Pemenuhan Persyaratan', score: 4, maxScore: 5, notes: 'Persyaratan terpenuhi dengan baik' },
      ],
      overallResult: 'Lolos',
      evaluatedBy: 'U002',
      evaluatedAt: '2025-11-15T11:00:00Z',
      notes: 'Layak melanjutkan ke Fase 2',
    },
    status: 'Selesai',
    evaluatedBy: 'U002',
    evaluatedAt: '2025-11-15T11:00:00Z',
  },
  // Fase 1 Evaluations for P002 (in progress)
  {
    id: 'EVAL-P1-003',
    projectId: 'P002',
    partnerId: 'M001',
    partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
    phase: 'phase1',
    phase1Eval: {
      partnerId: 'M001',
      partnerName: 'PT Perusahaan Gas Negara Tbk (PGN)',
      criteria: [
        { name: 'Kualitas Profil Perusahaan', score: 5, maxScore: 5, notes: 'PGN sebagai pemimpin gas nasional memiliki profil sangat kuat' },
        { name: 'Pengalaman Proyek Relevan', score: 5, maxScore: 5, notes: 'Pengalaman sangat relevan di bidang gas dan gasifikasi' },
        { name: 'Kemampuan Pembiayaan', score: 4, maxScore: 5, notes: 'Kemampuan pembiayaan baik untuk proyek >1T' },
        { name: 'Gambaran Umum Keuangan', score: 4, maxScore: 5, notes: 'Kondisi keuangan stabil' },
        { name: 'Pemenuhan Persyaratan', score: 5, maxScore: 5, notes: 'Semua persyaratan terpenuhi' },
      ],
      overallResult: 'Lolos',
      evaluatedBy: 'U002',
      evaluatedAt: '2026-01-10T09:00:00Z',
    },
    status: 'Selesai',
    evaluatedBy: 'U002',
    evaluatedAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'EVAL-P1-004',
    projectId: 'P002',
    partnerId: 'M005',
    partnerName: 'PT Indonesia Asahan Aluminium (INALUM)',
    phase: 'phase1',
    phase1Eval: {
      partnerId: 'M005',
      partnerName: 'PT Indonesia Asahan Aluminium (INALUM)',
      criteria: [
        { name: 'Kualitas Profil Perusahaan', score: 4, maxScore: 5, notes: 'Profil perusahaan baik sebagai holding BUMN' },
        { name: 'Pengalaman Proyek Relevan', score: 3, maxScore: 5, notes: 'Pengalaman terbatas di gasifikasi, lebih ke smelting' },
        { name: 'Kemampuan Pembiayaan', score: 5, maxScore: 5, notes: 'Kapasitas pembiayaan sangat kuat sebagai holding' },
        { name: 'Gambaran Umum Keuangan', score: 4, maxScore: 5, notes: 'Keuangan sehat' },
        { name: 'Pemenuhan Persyaratan', score: 3, maxScore: 5, notes: 'Beberapa persyaratan teknis belum optimal' },
      ],
      overallResult: 'Lolos',
      evaluatedBy: 'U002',
      evaluatedAt: '2026-01-10T10:00:00Z',
      notes: 'Lolos dengan catatan: perlu melengkapi pengalaman gasifikasi di Fase 2',
    },
    status: 'Selesai',
    evaluatedBy: 'U002',
    evaluatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'EVAL-P1-005',
    projectId: 'P002',
    partnerId: 'M006',
    partnerName: 'PT Pertamina New & Renewable Energy',
    phase: 'phase1',
    status: 'Draft',
    evaluatedBy: 'U002',
    evaluatedAt: '2026-01-10T11:00:00Z',
  },
];
