export { mockUsers } from './users';
export { mockProjects } from './projects';
export { mockPartners } from './partners';
export { mockEvaluations } from './evaluations';
export { mockApprovals } from './approvals';
export { mockDocuments } from './documents';
export type { DocumentWithMeta } from './documents';
export { mockNotifications } from './notifications';
export { dashboardStats, mockSLAItems } from './dashboard-stats';
export { mockApplications } from './applications';
