import { Notification } from '@/lib/types';

export const mockNotifications: Notification[] = [
  {
    id: 'NOTIF-001',
    title: 'Evaluasi Teknis PGN Telah Selesai',
    message: 'Evaluasi teknis PT Perusahaan Gas Negara Tbk untuk proyek Pengembangan PLTU Mulut Tambang 3x10 MW telah selesai dengan skor 4.25/5.00.',
    type: 'success',
    read: false,
    createdAt: '2026-03-04T08:30:00Z',
    link: '/projects/P001/evaluations/EVAL-001',
  },
  {
    id: 'NOTIF-002',
    title: 'SLA Proses Persetujuan Mendekati Batas',
    message: 'Proses persetujuan shortlist mitra untuk proyek Kerjasama Gasifikasi Batubara telah berjalan 12 dari 14 hari kerja yang ditargetkan. Segera tindak lanjuti.',
    type: 'warning',
    read: false,
    createdAt: '2026-03-03T14:15:00Z',
    link: '/approvals/APR-003',
  },
  {
    id: 'NOTIF-003',
    title: 'Dokumen Mitra AKR Ditolak',
    message: 'Laporan Keuangan 2023 PT AKR Corporindo Tbk ditolak karena belum diaudit oleh KAP terdaftar di OJK. Mohon koordinasi dengan mitra untuk perbaikan.',
    type: 'error',
    read: false,
    createdAt: '2026-03-03T10:45:00Z',
    link: '/partners/M003/documents',
  },
  {
    id: 'NOTIF-004',
    title: 'Persetujuan Evaluasi Teknis PLTU Disetujui',
    message: 'Ir. Bambang Wijaya telah menyetujui hasil evaluasi teknis untuk proyek Pengembangan PLTU Mulut Tambang 3x10 MW.',
    type: 'success',
    read: true,
    createdAt: '2026-03-02T16:00:00Z',
    link: '/approvals/APR-002',
  },
  {
    id: 'NOTIF-005',
    title: 'Mitra Baru Terdaftar: PNRE',
    message: 'PT Pertamina New & Renewable Energy telah terdaftar sebagai calon mitra. Status saat ini: Dalam Review. 4 dari 17 dokumen belum lengkap.',
    type: 'info',
    read: true,
    createdAt: '2026-03-02T09:20:00Z',
    link: '/partners/M006',
  },
  {
    id: 'NOTIF-006',
    title: 'Dokumen PNRE Menunggu Verifikasi',
    message: 'Laporan Keuangan 2023 PT Pertamina New & Renewable Energy telah diupload dan menunggu verifikasi dari tim keuangan.',
    type: 'info',
    read: false,
    createdAt: '2026-03-01T11:30:00Z',
    link: '/partners/M006/documents',
  },
  {
    id: 'NOTIF-007',
    title: 'Persetujuan Inisiasi Proyek Menunggu',
    message: 'Persetujuan inisiasi proyek Coal-to-Methanol Plant senilai Rp 2.5T menunggu persetujuan Dr. Maya Putri (Komisaris) sejak 15 Januari 2026.',
    type: 'warning',
    read: false,
    createdAt: '2026-02-28T08:00:00Z',
    link: '/approvals/APR-005',
  },
  {
    id: 'NOTIF-008',
    title: 'Evaluasi Keuangan INALUM Selesai',
    message: 'Evaluasi keuangan KEP-100 PT INALUM untuk proyek Gasifikasi Batubara selesai. Skor: 77.90, Grade: A.',
    type: 'success',
    read: true,
    createdAt: '2026-02-27T15:45:00Z',
    link: '/projects/P002/evaluations/EVAL-002',
  },
  {
    id: 'NOTIF-009',
    title: 'Proyek Rehabilitasi Lahan Selesai',
    message: 'Proyek Rehabilitasi Lahan Pasca Tambang (P005) telah dinyatakan selesai. Seluruh tahapan 13/13 telah diselesaikan.',
    type: 'success',
    read: true,
    createdAt: '2026-02-25T10:00:00Z',
    link: '/projects/P005',
  },
  {
    id: 'NOTIF-010',
    title: 'Persetujuan Legal Gasifikasi Dikembalikan',
    message: 'Persetujuan hasil evaluasi legal proyek Gasifikasi Batubara dikembalikan oleh Ir. Bambang Wijaya. Perlu klarifikasi tambahan terkait sengketa lahan INALUM.',
    type: 'error',
    read: false,
    createdAt: '2026-02-24T13:20:00Z',
    link: '/approvals/APR-006',
  },
  {
    id: 'NOTIF-011',
    title: 'Daftar Tenaga Ahli AKR Ditolak',
    message: 'Daftar Tenaga Ahli PT AKR Corporindo Tbk ditolak. Kualifikasi tenaga ahli bidang kimia dan petrokimia belum memenuhi persyaratan minimum proyek.',
    type: 'error',
    read: true,
    createdAt: '2026-02-22T09:15:00Z',
    link: '/partners/M003/documents',
  },
  {
    id: 'NOTIF-012',
    title: 'Deadline Evaluasi P001 Dalam 7 Hari',
    message: 'Batas waktu penyelesaian evaluasi mitra untuk proyek PLTU Mulut Tambang 3x10 MW adalah 7 hari lagi (11 Maret 2026). Pastikan seluruh evaluasi selesai tepat waktu.',
    type: 'warning',
    read: false,
    createdAt: '2026-02-20T07:00:00Z',
    link: '/projects/P001',
  },
  {
    id: 'NOTIF-013',
    title: 'Solar Panel Farm Masuk Tahap Persetujuan',
    message: 'Proyek Solar Panel Farm Tanjung Enim (P003) telah memasuki tahap persetujuan akhir (step 12/13). Menunggu persetujuan Direksi.',
    type: 'info',
    read: true,
    createdAt: '2026-02-18T14:30:00Z',
    link: '/projects/P003',
  },
  {
    id: 'NOTIF-014',
    title: 'Sertifikat ISO PGN Akan Kedaluwarsa',
    message: 'Sertifikat ISO 9001:2015 PT PGN akan kedaluwarsa pada 30 September 2026. Mohon ingatkan mitra untuk melakukan pembaruan sertifikat.',
    type: 'warning',
    read: true,
    createdAt: '2026-02-15T10:00:00Z',
    link: '/partners/M001/documents',
  },
  {
    id: 'NOTIF-015',
    title: 'Dokumen Mitra PNRE Belum Lengkap',
    message: 'PT Pertamina New & Renewable Energy masih memiliki 4 dokumen dengan status belum lengkap: Sertifikat ISO, Laporan Keuangan (Pending), Daftar Peralatan, dan Jaminan Penawaran.',
    type: 'warning',
    read: false,
    createdAt: '2026-02-12T08:45:00Z',
    link: '/partners/M006/documents',
  },
];
