import { Project } from '@/lib/types';

export const mockProjects: Project[] = [
  {
    id: 'P001',
    name: 'Pengembangan PLTU Mulut Tambang 3x10 MW',
    type: 'CAPEX',
    status: 'Evaluasi',
    capexValue: 450000000000,
    description:
      'Proyek pembangunan Pembangkit Listrik Tenaga Uap (PLTU) mulut tambang dengan kapasitas 3x10 MW di kawasan pertambangan Tanjung Enim. Proyek ini bertujuan untuk meningkatkan efisiensi pemanfaatan batubara kualitas rendah yang tidak ekonomis untuk dijual, sekaligus mendukung kebutuhan listrik operasional tambang dan kawasan sekitar.',
    startDate: '2025-06-01',
    endDate: '2027-12-31',
    currentStep: 9,
    totalSteps: 13,
    partners: ['M001', 'M004'],
    createdBy: 'U002',
    createdAt: '2025-05-15T08:30:00Z',
    isOpenForApplication: false,
    applicationDeadline: '2026-03-30',
    prdDocument: 'PRD_PLTU_Mulut_Tambang_3x10MW.pdf',
    requirements: [
      'Pengalaman minimal 5 tahun di bidang pembangkit listrik tenaga uap',
      'Memiliki sertifikasi ISO 9001 dan ISO 14001',
      'Kemampuan pendanaan minimal 30% dari nilai CAPEX proyek',
      'Memiliki tenaga ahli bersertifikat di bidang PLTU',
      'Track record proyek pembangkit listrik dengan kapasitas minimal 10 MW',
    ],
    requiredDocuments: [
      'akta_pendirian', 'siup', 'tdp_nib', 'npwp', 'laporan_keuangan',
      'referensi_bank', 'pengalaman_kerja', 'sertifikat_iso', 'amdal_ukl_upl',
      'profil_perusahaan', 'struktur_organisasi', 'daftar_peralatan', 'daftar_tenaga_ahli',
    ],
    phase: 'phase2_evaluation',
    picAssignments: [
      { role: 'ebd', userId: 'U002', userName: 'Siti Rahmawati' },
      { role: 'keuangan', userId: 'U003', userName: 'Ahmad Hidayat' },
      { role: 'hukum', userId: 'U004', userName: 'Dewi Lestari' },
      { role: 'risiko', userId: 'U005', userName: 'Rudi Hartono' },
      { role: 'direksi', userId: 'U006', userName: 'Ir. Bambang Wijaya' },
    ],
    shortlistedPartners: ['M001', 'M004'],
    phase1Deadline: '2025-12-31',
    phase2Deadline: '2026-03-30',
    phase1Documents: ['statement_eoi', 'compro', 'portfolio', 'financial_overview', 'requirements_fulfillment'],
    phase2Documents: ['confidential_guarantee_signed', 'loi_signed', 'proposal_detail', 'financial_detail', 'info_detail'],
    ptbaDocuments: [
      { id: 'PTBA-DOC-001', name: 'Business Case PLTU 3x10 MW', type: 'Business Case' },
      { id: 'PTBA-DOC-002', name: 'Confidential Guarantee Statement', type: 'Confidential Guarantee' },
      { id: 'PTBA-DOC-003', name: 'Letter of Intent Template', type: 'LoI' },
      { id: 'PTBA-DOC-004', name: 'Request for Proposal (RfP)', type: 'RfP' },
    ],
    registrationFee: 50000000,
  },
  {
    id: 'P002',
    name: 'Kerjasama Gasifikasi Batubara',
    type: 'Strategis',
    status: 'Evaluasi',
    capexValue: 1200000000000,
    description:
      'Proyek kerjasama strategis gasifikasi batubara untuk mengkonversi batubara menjadi syngas (gas sintesis) yang dapat digunakan sebagai bahan baku industri kimia dan bahan bakar. Proyek ini merupakan bagian dari strategi diversifikasi produk turunan batubara PTBA dan mendukung program hilirisasi batubara nasional.',
    startDate: '2025-03-01',
    endDate: '2029-06-30',
    currentStep: 7,
    totalSteps: 13,
    partners: ['M001', 'M005', 'M006'],
    createdBy: 'U002',
    createdAt: '2025-02-10T10:00:00Z',
    isOpenForApplication: false,
    applicationDeadline: '2025-12-15',
    prdDocument: 'PRD_Gasifikasi_Batubara_Coal_to_SNG.pdf',
    requirements: [
      'Pengalaman di sektor gas dan/atau energi minimal 10 tahun',
      'Memiliki infrastruktur distribusi gas atau akses ke jaringan distribusi',
      'Kemampuan pendanaan untuk proyek bernilai lebih dari Rp 1 Triliun',
      'Memiliki teknologi gasifikasi atau kemitraan dengan penyedia teknologi',
    ],
    requiredDocuments: [
      'akta_pendirian', 'siup', 'tdp_nib', 'npwp', 'laporan_keuangan',
      'referensi_bank', 'pengalaman_kerja', 'sertifikat_iso', 'amdal_ukl_upl',
      'profil_perusahaan', 'struktur_organisasi', 'daftar_peralatan', 'daftar_tenaga_ahli',
    ],
    phase: 'phase1_approved',
    picAssignments: [
      { role: 'ebd', userId: 'U002', userName: 'Siti Rahmawati' },
      { role: 'keuangan', userId: 'U003', userName: 'Ahmad Hidayat' },
      { role: 'hukum', userId: 'U004', userName: 'Dewi Lestari' },
      { role: 'risiko', userId: 'U005', userName: 'Rudi Hartono' },
      { role: 'direksi', userId: 'U006', userName: 'Ir. Bambang Wijaya' },
    ],
    shortlistedPartners: ['M001', 'M005'],
    phase1Deadline: '2025-12-15',
    phase2Deadline: '2026-04-15',
    phase1Documents: ['statement_eoi', 'compro', 'portfolio', 'financial_overview', 'requirements_fulfillment'],
    phase2Documents: ['confidential_guarantee_signed', 'loi_signed', 'proposal_detail', 'financial_detail', 'info_detail'],
    ptbaDocuments: [
      { id: 'PTBA-DOC-005', name: 'Business Case Gasifikasi Batubara', type: 'Business Case' },
      { id: 'PTBA-DOC-006', name: 'Confidential Guarantee Statement', type: 'Confidential Guarantee' },
      { id: 'PTBA-DOC-007', name: 'Letter of Intent Template', type: 'LoI' },
      { id: 'PTBA-DOC-008', name: 'Request for Proposal (RfP)', type: 'RfP' },
    ],
    registrationFee: 100000000,
  },
  {
    id: 'P003',
    name: 'Solar Panel Farm Tanjung Enim',
    type: 'CAPEX',
    status: 'Persetujuan',
    capexValue: 85000000000,
    description:
      'Pembangunan pembangkit listrik tenaga surya (PLTS) di lahan pasca tambang kawasan Tanjung Enim dengan kapasitas 15 MWp. Proyek ini merupakan komitmen PTBA dalam transisi energi dan pemanfaatan lahan reklamasi pasca tambang secara produktif untuk energi terbarukan.',
    startDate: '2025-09-01',
    endDate: '2026-12-31',
    currentStep: 12,
    totalSteps: 13,
    partners: ['M006'],
    createdBy: 'U006',
    createdAt: '2025-08-01T09:15:00Z',
    isOpenForApplication: false,
    winnerId: 'M006',
    phase: 'phase2_approval',
    picAssignments: [
      { role: 'ebd', userId: 'U010', userName: 'Fitri Handayani' },
      { role: 'keuangan', userId: 'U003', userName: 'Ahmad Hidayat' },
      { role: 'hukum', userId: 'U004', userName: 'Dewi Lestari' },
      { role: 'risiko', userId: 'U005', userName: 'Rudi Hartono' },
      { role: 'direksi', userId: 'U006', userName: 'Ir. Bambang Wijaya' },
    ],
    shortlistedPartners: ['M006'],
  },
  {
    id: 'P004',
    name: 'Coal-to-Methanol Plant',
    type: 'Strategis',
    status: 'Draft',
    capexValue: 2500000000000,
    description:
      'Proyek pembangunan pabrik konversi batubara menjadi metanol (Coal-to-Methanol) dengan kapasitas produksi 600.000 ton per tahun. Metanol yang dihasilkan akan digunakan sebagai bahan baku industri kimia dan campuran bahan bakar. Proyek ini merupakan flagship project dalam program hilirisasi batubara PTBA.',
    startDate: '2026-01-01',
    endDate: '2030-12-31',
    currentStep: 2,
    totalSteps: 13,
    partners: ['M003', 'M004'],
    createdBy: 'U002',
    createdAt: '2025-11-20T14:00:00Z',
    isOpenForApplication: true,
    applicationDeadline: '2026-05-30',
    prdDocument: 'PRD_Coal_to_Methanol_Plant.pdf',
    requirements: [
      'Pengalaman di industri petrokimia atau konversi batubara minimal 10 tahun',
      'Memiliki lisensi teknologi Coal-to-Methanol atau kemitraan dengan pemilik teknologi',
      'Kemampuan pendanaan minimal Rp 500 Miliar',
      'Sertifikasi ISO 9001, ISO 14001, dan OHSAS 18001',
    ],
    requiredDocuments: [
      'akta_pendirian', 'siup', 'tdp_nib', 'npwp', 'laporan_keuangan',
      'referensi_bank', 'pengalaman_kerja', 'sertifikat_iso', 'amdal_ukl_upl',
      'profil_perusahaan', 'struktur_organisasi',
    ],
    phase: 'phase1_registration',
    phase1Deadline: '2026-05-30',
    phase2Deadline: '2026-09-30',
    phase1Documents: ['statement_eoi', 'compro', 'portfolio', 'financial_overview', 'requirements_fulfillment'],
    phase2Documents: ['confidential_guarantee_signed', 'loi_signed', 'proposal_detail', 'financial_detail', 'info_detail'],
    ptbaDocuments: [
      { id: 'PTBA-DOC-009', name: 'Business Case Coal-to-Methanol', type: 'Business Case' },
      { id: 'PTBA-DOC-010', name: 'Confidential Guarantee Statement', type: 'Confidential Guarantee' },
    ],
    registrationFee: 150000000,
  },
  {
    id: 'P005',
    name: 'Rehabilitasi Lahan Pasca Tambang',
    type: 'OPEX',
    status: 'Selesai',
    capexValue: 15000000000,
    description:
      'Program rehabilitasi dan reklamasi lahan pasca tambang seluas 500 hektar di kawasan Muara Enim. Proyek mencakup penataan lahan, revegetasi dengan tanaman produktif, pembangunan infrastruktur pendukung, dan pengembangan potensi ekowisata di area reklamasi.',
    startDate: '2024-01-15',
    endDate: '2025-12-31',
    currentStep: 13,
    totalSteps: 13,
    partners: ['M005'],
    createdBy: 'U010',
    createdAt: '2023-12-01T07:45:00Z',
    isOpenForApplication: false,
    winnerId: 'M005',
    winnerAnnouncedAt: '2025-12-15T10:00:00Z',
    phase: 'completed',
    shortlistedPartners: ['M005'],
    picAssignments: [
      { role: 'ebd', userId: 'U010', userName: 'Fitri Handayani' },
      { role: 'keuangan', userId: 'U003', userName: 'Ahmad Hidayat' },
      { role: 'hukum', userId: 'U004', userName: 'Dewi Lestari' },
      { role: 'risiko', userId: 'U005', userName: 'Rudi Hartono' },
      { role: 'direksi', userId: 'U006', userName: 'Ir. Bambang Wijaya' },
    ],
  },
];
